const colors = require('tailwindcss/colors')

module.exports = {
  purge: {
    content: [
      './components/**/*.{js,ts,jsx,tsx}',
      './pages/**/*.{js,ts,jsx,tsx,mdx}',
    ],
    options: {
      safelist: [
        'font-thin',
        'font-extralight',
        'font-light',
        'font-normal',
        'font-medium',
        'font-semibold',
        'font-bold',
        'font-extrabold',
        'font-black',
        'rounded-none',
        'rounded-sm',
        'rounded',
        'rounded-md',
        'rounded-lg',
        'rounded-xl',
        'rounded-2xl',
        'rounded-3xl',
        'rounded-full',
        'px-px',
        'px-0',
        'px-0.5',
        'px-1',
        'px-1.5',
        'px-2',
        'px-2.5',
        'px-3',
        'px-3.5',
        'px-4',
        'px-5',
        'px-6',
        'px-7',
        'px-8',
        'px-9',
        'px-10',
        'py-px',
        'py-0',
        'py-0.5',
        'py-1',
        'py-1.5',
        'py-2',
        'py-2.5',
        'py-3',
        'py-3.5',
        'py-4',
        'py-5',
        'py-6',
        'py-7',
        'py-8',
        'p-px',
        'p-0',
        'p-0.5',
        'p-1',
        'p-1.5',
        'p-2',
        'p-2.5',
        'p-3',
        'p-3.5',
        'p-4',
        'p-5',
        'p-6',
        'p-7',
        'p-8',
        'bg-blueGray-100',
        'bg-blueGray-200',
        'bg-blueGray-800',
        'bg-blueGray-900',
        'text-blueGray-50',
        'text-blueGray-900',
        'border-blueGray-600',
        'border-blueGray-300',
        'ring-blueGray-500',
        'bg-coolGray-200',
        'text-coolGray-900',
        'bg-coolGray-100',
        'ring-coolGray-500',
        'bg-coolGray-900',
        'text-coolGray-50',
        'border-coolGray-600',
        'border-coolGray-300',
        'bg-coolGray-800',
        'bg-gray-200',
        'text-gray-900',
        'bg-gray-100',
        'ring-gray-500',
        'bg-gray-900',
        'text-gray-50',
        'border-gray-600',
        'border-gray-300',
        'bg-gray-800',
        'bg-trueGray-200',
        'text-trueGray-900',
        'bg-trueGray-100',
        'ring-trueGray-500',
        'bg-trueGray-900',
        'text-trueGray-50',
        'border-trueGray-600',
        'border-trueGray-300',
        'bg-trueGray-800',
        'bg-warmGray-200',
        'text-warmGray-900',
        'bg-warmGray-100',
        'ring-warmGray-500',
        'bg-warmGray-900',
        'text-warmGray-50',
        'border-warmGray-600',
        'border-warmGray-300',
        'bg-warmGray-800',
        'bg-red-200',
        'text-red-900',
        'bg-red-100',
        'ring-red-500',
        'bg-red-900',
        'text-red-50',
        'border-red-600',
        'border-red-300',
        'bg-red-800',
        'bg-orange-200',
        'text-orange-900',
        'bg-orange-100',
        'ring-orange-500',
        'bg-orange-900',
        'text-orange-50',
        'border-orange-600',
        'border-orange-300',
        'bg-orange-800',
        'bg-amber-200',
        'text-amber-900',
        'bg-amber-100',
        'ring-amber-500',
        'bg-amber-900',
        'text-amber-50',
        'border-amber-600',
        'border-amber-300',
        'bg-amber-800',
        'bg-yellow-200',
        'text-yellow-900',
        'bg-yellow-100',
        'ring-yellow-500',
        'bg-yellow-900',
        'text-yellow-50',
        'border-yellow-600',
        'border-yellow-300',
        'bg-yellow-800',
        'bg-lime-200',
        'text-lime-900',
        'bg-lime-100',
        'ring-lime-500',
        'bg-lime-900',
        'text-lime-50',
        'border-lime-600',
        'border-lime-300',
        'bg-lime-800',
        'bg-green-200',
        'text-green-900',
        'bg-green-100',
        'ring-green-500',
        'bg-green-900',
        'text-green-50',
        'border-green-600',
        'border-green-300',
        'bg-green-800',
        'bg-emerald-200',
        'text-emerald-900',
        'bg-emerald-100',
        'ring-emerald-500',
        'bg-emerald-900',
        'text-emerald-50',
        'border-emerald-600',
        'border-emerald-300',
        'bg-emerald-800',
        'bg-teal-200',
        'text-teal-900',
        'bg-teal-100',
        'ring-teal-500',
        'bg-teal-900',
        'text-teal-50',
        'border-teal-600',
        'border-teal-300',
        'bg-teal-800',
        'bg-cyan-200',
        'text-cyan-900',
        'bg-cyan-100',
        'ring-cyan-500',
        'bg-cyan-900',
        'text-cyan-50',
        'border-cyan-600',
        'border-cyan-300',
        'bg-cyan-800',
        'bg-lightBlue-200',
        'text-lightBlue-900',
        'bg-lightBlue-100',
        'ring-lightBlue-500',
        'bg-lightBlue-900',
        'text-lightBlue-50',
        'border-lightBlue-600',
        'border-lightBlue-300',
        'bg-lightBlue-800',
        'bg-blue-200',
        'text-blue-900',
        'bg-blue-100',
        'ring-blue-500',
        'bg-blue-900',
        'text-blue-50',
        'border-blue-600',
        'border-blue-300',
        'bg-blue-800',
        'bg-indigo-200',
        'text-indigo-900',
        'bg-indigo-100',
        'ring-indigo-500',
        'bg-indigo-900',
        'text-indigo-50',
        'border-indigo-600',
        'border-indigo-300',
        'bg-indigo-800',
        'bg-violet-200',
        'text-violet-900',
        'bg-violet-100',
        'ring-violet-500',
        'bg-violet-900',
        'text-violet-50',
        'border-violet-600',
        'border-violet-300',
        'bg-violet-800',
        'bg-purple-200',
        'text-purple-900',
        'bg-purple-100',
        'ring-purple-500',
        'bg-purple-900',
        'text-purple-50',
        'border-purple-600',
        'border-purple-300',
        'bg-purple-800',
        'bg-fuchsia-200',
        'text-fuchsia-900',
        'bg-fuchsia-100',
        'ring-fuchsia-500',
        'bg-fuchsia-900',
        'text-fuchsia-50',
        'border-fuchsia-600',
        'border-fuchsia-300',
        'bg-fuchsia-800',
        'bg-pink-200',
        'text-pink-900',
        'bg-pink-100',
        'ring-pink-500',
        'bg-pink-900',
        'text-pink-50',
        'border-pink-600',
        'border-pink-300',
        'bg-pink-800',
        'bg-rose-200',
        'text-rose-900',
        'bg-rose-100',
        'ring-rose-500',
        'bg-rose-900',
        'text-rose-50',
        'border-rose-600',
        'border-rose-300',
        'bg-rose-800',
      ],
    },
  },
  darkMode: 'media',
  theme: {
    // https://tailwindcss.com/docs/customizing-colors
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      black: colors.black,
      white: colors.white,
      blueGray: colors.blueGray,
      coolGray: colors.coolGray,
      gray: colors.gray,
      trueGray: colors.trueGray,
      warmGray: colors.warmGray,
      red: colors.red,
      orange: colors.orange,
      amber: colors.amber,
      yellow: colors.yellow,
      lime: colors.lime,
      green: colors.green,
      emerald: colors.emerald,
      teal: colors.teal,
      cyan: colors.cyan,
      lightBlue: colors.lightBlue,
      blue: colors.blue,
      indigo: colors.indigo,
      violet: colors.violet,
      purple: colors.purple,
      fuchsia: colors.fuchsia,
      pink: colors.pink,
      rose: colors.rose,
    },
  },
  variants: {},
  plugins: [],
}
