export type GlobalContextType = {
  state: State
  dispatch: React.Dispatch<Actions>
}

export type Actions = {
  type:
    | 'COLOR'
    | 'ROUNDED'
    | 'PADDING_Y'
    | 'PADDING_X'
    | 'PADDING'
    | 'FONT_WEIGHT'
    | 'CLIPBOARD'
  payload?: string
}

export type State = {
  color:
    | 'blueGray'
    | 'coolGray'
    | 'gray'
    | 'trueGray'
    | 'warmGray'
    | 'red'
    | 'orange'
    | 'amber'
    | 'yellow'
    | 'lime'
    | 'green'
    | 'emerald'
    | 'teal'
    | 'cyan'
    | 'lightBlue'
    | 'blue'
    | 'indigo'
    | 'violet'
    | 'purple'
    | 'fuchsia'
    | 'pink'
    | 'rose'
  rounded:
    | 'rounded-none'
    | 'rounded-sm'
    | 'rounded'
    | 'rounded-md'
    | 'rounded-lg'
    | 'rounded-xl'
    | 'rounded-2xl'
    | 'rounded-3xl'
    | 'rounded-full'
  fontWeight:
    | 'font-thin'
    | 'font-extralight'
    | 'font-light'
    | 'font-normal'
    | 'font-medium'
    | 'font-semibold'
    | 'font-bold'
    | 'font-extrabold'
    | 'font-black'
  paddingX:
    | 'px-px'
    | 'px-0'
    | 'px-0.5'
    | 'px-1'
    | 'px-1.5'
    | 'px-2'
    | 'px-2.5'
    | 'px-3'
    | 'px-3.5'
    | 'px-4'
    | 'px-5'
    | 'px-6'
    | 'px-7'
    | 'px-8'
    | 'px-9'
    | 'px-10'
  paddingY:
    | 'py-px'
    | 'py-0'
    | 'py-0.5'
    | 'py-1'
    | 'py-1.5'
    | 'py-2'
    | 'py-2.5'
    | 'py-3'
    | 'py-3.5'
    | 'py-4'
    | 'py-5'
    | 'py-6'
    | 'py-7'
    | 'py-8'
  padding:
    | 'p-px'
    | 'p-0'
    | 'p-0.5'
    | 'p-1'
    | 'p-1.5'
    | 'p-2'
    | 'p-2.5'
    | 'p-3'
    | 'p-3.5'
    | 'p-4'
    | 'p-5'
    | 'p-6'
    | 'p-7'
    | 'p-8'
}
